#!/usr/bin/env python3
import sys
import os

script_dir = os.path.dirname(__file__)
sys.path.insert(0, os.path.join(script_dir, "pylibs"))

import loggy

loggy.enabled = True
paths = os.environ["PATH"].split(os.pathsep)

path_index = 0
for path in paths:
    print("%s '%s'" % (path_index, path))
    path_index += 1

def prompt_path():
    while True:
        sys.stdout.write("which path would you like to install to? ")
        response = input()
        try:
            index = int(response)
            if index < len(paths):
                return index
        except ValueError:
            pass

selected_index = prompt_path()
# TODO: handle special characters in the path like '~' or environment variables like '$HOME'
loggy.run(["ln", "-s", os.path.abspath(os.path.join(script_dir, "treepack")),
           os.path.join(paths[selected_index], "treepack")])
